// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EvaluateDataset
List EvaluateDataset(Rcpp::NumericMatrix in_data, Rcpp::NumericMatrix out_data);
RcppExport SEXP _RSPANNGPU_EvaluateDataset(SEXP in_dataSEXP, SEXP out_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type in_data(in_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type out_data(out_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(EvaluateDataset(in_data, out_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSPANNGPU_EvaluateDataset", (DL_FUNC) &_RSPANNGPU_EvaluateDataset, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSPANNGPU(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
