# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EvaluateDataset <- function(in_data, out_data) {
    .Call(`_RSPANNGPU_EvaluateDataset`, in_data, out_data)
}

